name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04  # নির্দিষ্ট ভার্সন দিলে স্ট্যাবল থাকে
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev zip unzip libtool autoconf cmake gettext
          pip install --upgrade pip
          pip install buildozer kivy

      - name: Build with Buildozer
        run: |
          # সব লাইসেন্স অটো-একসেপ্ট করে বিল্ড শুরু করবে
          yes | buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/*.apk
