name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # সরাসরি বিল্ডোজার অ্যাকশন ব্যবহার (এটি সবথেকে স্ট্যাবল)
      - name: Buildozer Android Action
        uses: ArtemSerebrennkov/buildozer-action@v1.6.1
        with:
          command: buildozer android debug
          repository_root: .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/*.apk
